### ISSUE TITLE
Create Text model

### ISSUE THREAD

**Issue by WendelHime** [CapivaraProjects/GYResources#1]
We need to create a Text model with this attributes:

| Attributes | Description |
| :-- | :-- |
| id |  Text ID |
| language | Language |
| tag | Tag identification |
| value | Text value |
| description | Description about text |

**Comment by renanfox2** [comment]
Attributes | Description
-- | --
id | Text ID
language | Language
tag | Tag identification
value | Text value
description | Description about text
