### ISSUE TITLE
Add tensorflow_serving repository to Dockerfile

### ISSUE THREAD

**Issue by BiondiVini** [CapivaraProjects/GYResources#102]
Add and tensorflow_serving repository and dependencies to Dockerfile in accordance with this 

[Tensorflow Serving Tutorial](https://www.tensorflow.org/serving/setup)
[Tensorflow Serving Repository](https://github.com/tensorflow/serving.git)

**Comment by WendelHime** [comment]
Docker should build with Nvidia-Docker or normal Docker?

**Comment by BiondiVini** [comment]
For Tensorflow Serving has no GPU dependencies, then build it with a normal Docker.

**Comment by WendelHime** [comment]
This issue should really stay here? Or it should be on gykernel project?

**Comment by BiondiVini** [comment]
Moved to [gykernel #2 ](https://github.com/CapivaraProjects/gykernel/issues/2)
