### ISSUE TITLE
Create Plant repository (with CRUD)

### ISSUE THREAD

**Issue by WendelHime** [CapivaraProjects/GYResources#17]
Create Plant repository (CRUD) using Plant ORM model(capivaraprojects.greeneyes.database) which returns always a Plant model(from capivaraprojects.greeneyes.models) 

WITH UNITARY TESTS USING `pytest`

**Comment by WendelHime** [comment]
Search function should have parameters to limit a range of results

```python3
pageSize = 10
offset = 10
search(pageSize, offset)
    assert len([]) = 10
```

**Comment by BiondiVini** [comment]
closed by https://github.com/CapivaraProjects/repository/pull/6
